name: Unity Build

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Unity
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 2022.3.22f1

    - name: Build project
      uses: game-ci/unity-builder@v2
      with:
        targetPlatform: StandaloneWindows64
        unityVersion: 2021.1.10f1

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: build
